spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PheaSoy/spring-cloud-config
    bus:
      trace:
        enabled: true
        
  rabbitmq:
    username: guest
    password: guest
    port: 5672
    host: localhost
server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'