spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PheaSoy/spring-cloud-config
        token: s.a39HDWx5BkjOUVkcAy9V6Kog
    bus:
      trace:
        enabled: true

  rabbitmq:
    username: guest
    password: guest
    port: 5672
    host: localhost
server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: '*'