management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - beans
          - bus-refresh
spring:
  rabbitmq:
    username: guest
    password: guest
    port: 5672
    host: localhost
